### ISSUE TITLE
已发现的问题

### ISSUE THREAD

**Issue by cczhr** [cczhr/OTGLocation#1]
2021.3.2
有部分手机厂商的定制系统一插入 iPhone 会弹出文件管理器占用了 usb 端口，导致无法连接。（在V1.0.1上已修复）
userdebug编译自带root的系统system写入权限失败。（在V1.0.1上已修复）

**Comment by merhong2012** [comment]
补充错误日志：
<img width="323" alt="WX20210302-113547@2x" src="https://user-images.githubusercontent.com/7665010/109593271-9e16f380-7b4b-11eb-95c9-892b487dc62d.png">

**Comment by cczhr** [comment]
@merhong2012  已修复 可以下载1.0.1版本试试 连接时有可能系统会弹“xxx已停止的框” 这是因为我软件强制停止了占用usb设备的进程，不影响使用。
https://github.com/cczhr/OTGLocation/releases/tag/V1.0.1

**Comment by merhong2012** [comment]
> @merhong2012 已修复 可以下载1.0.1版本试试 连接时有可能系统会弹“xxx已停止的框” 这是因为我软件强制停止了占用usb设备的进程，不影响使用。
> https://github.com/cczhr/OTGLocation/releases/tag/V1.0.1

测试后可以了。加个坐标收藏就更完美了~

**Comment by cczhr** [comment]
@merhong2012 嗯嗯 下次更新应该会加上

**Comment by lianghao721** [comment]
弱弱的问一句android手机不需要root的吧~
