### ISSUE TITLE
设备连接不上

### ISSUE THREAD

**Issue by autught** [cczhr/OTGLocation#11]
连接之后控制台打印unable to start "proc/self/exe":No such file or directory
手机是root的，线也换了两根，请问这是什么问题呢

**Comment by cczhr** [comment]
> 连接之后控制台打印unable to start "proc/self/exe":No such file or directory 手机是root的，线也换了两根，请问这是什么问题呢

这个问题可能和android系统有关 这个app有的设备是用不了

**Comment by autught** [comment]
![Screenshot_2022-03-03-12-32-59-941_com cczhr otglocation](https://user-images.githubusercontent.com/32406771/156496827-d03f9b51-ee4a-4dc9-89ca-0e52a89047c1.jpg)
多谢你的回复，我换个红米note5试了下出现这个，这能看出来是什么问题吗
node=/dev/bus/usb/001/002 fd=53
sh: <stdin>[2]: awk: not found
sh: <stdin>[2]: awk: not found
usage: kill [-s signame | -signum | -signame]{job | pid |pgrp }...
kill -l [exit_status ...]

**Comment by cczhr** [comment]
> ![Screenshot_2022-03-03-12-32-59-941_com cczhr otglocation](https://user-images.githubusercontent.com/32406771/156496827-d03f9b51-ee4a-4dc9-89ca-0e52a89047c1.jpg) 多谢你的回复，我换个红米note5试了下出现这个，这能看出来是什么问题吗 node=/dev/bus/usb/001/002 fd=53 sh: [2]: awk: not found sh: [2]: awk: not found usage: kill [-s signame | -signum | -signame]{job | pid |pgrp }... kill -l [exit_status ...]

看不出 应该是正常的 可以试试重新插拔 你用的是什么线

**Comment by autught** [comment]
就是网上买的，一端是usb，另一端是Micro-usb,链接苹果手机的就是正常的苹果充电线

**Comment by autught** [comment]
可能就是线的问题吧，连接上之后，苹果手机都没弹是否信任那个窗口
