### ISSUE TITLE
大佬 能否增加提示 和 快捷选择

### ISSUE THREAD

**Issue by BlingRbt** [cczhr/OTGLocation#14]
1.大佬 能否增加在输出框显示是否成功修改经纬度和恢复经纬度
有时候没注意弹出 不知道是否修改成功
2.能否在修改定位上面加一个小选项 快速选择已有位置 直接修改？
![Screenshot_2022-04-08-12-36-44-134_com cczhr otglocation](https://user-images.githubusercontent.com/10525250/162417734-0a3f8a54-c773-4bf6-b184-26b3ed0a7092.jpg)

**Comment by cczhr** [comment]
> 1.大佬 能否增加在输出框显示是否成功修改经纬度和恢复经纬度 有时候没注意弹出 不知道是否修改成功 2.能否在修改定位上面加一个小选项 快速选择已有位置 直接修改？ ![Screenshot_2022-04-08-12-36-44-134_com cczhr otglocation](https://user-images.githubusercontent.com/10525250/162417734-0a3f8a54-c773-4bf6-b184-26b3ed0a7092.jpg)

加了 https://github.com/cczhr/OTGLocation/releases/tag/V1.1.4

**Comment by BlingRbt** [comment]
牛逼大佬！！！
对了 关于免root的 git上没有搜到类似的 大佬有方向吗
