### ISSUE TITLE
小米9USB无法连接

### ISSUE THREAD

**Issue by fhdjasklf** [cczhr/OTGLocation#16]
系统是MIUI12 EU稳定版全新安装完,Magisk Root,安装组件显示成功.
用type-c转接usb-a然后连iphone12,系统会自动跳出弹窗让我选择文件管理器打开,打开之后也可以显示iphone的照片.
退回软件可以显示USB授权,授权完成之后一直设备连接状态是“未挂载”,换了直连的线也不可以
能麻烦帮忙看看不?
```
node=/dev/bus/usb/001/003 fd=99
[16:22:07.915][3] usbmuxd v1.1.2 starting up
[16:22:07.921][3] Caught signal 15, exiting
[16:22:07.921][3] Sending signal 15 to instance with pid 16878
[16:22:07.921][4] Event processing interrupted
[16:22:07.921][3] usbmuxd shutting down
[16:22:10.875][3] usbmuxd v1.1.2 starting up
[16:22:10.882][4] Creating socket
[16:22:10.882][4] socket port:27015
[16:22:10.882][4] Listening on /var/run/usbmuxd
[16:22:10.882][4] Initializing USB
[16:22:10.882][3] Using libusb 1.0.24
[16:22:10.884][4] Registering for libusb hotplug events
[16:22:10.884][4] Found new device with v/p 05ac:12a8 at 1-3
[16:22:10.884][4] Setting configuration for device 1-3, from 1 to 4
[16:22:10.884][2] Could not set configuration 4 for device 1-3: LIBUSB_ERROR_BUSY
[16:22:10.884][4] 0 devices detected
[16:22:10.884][3] Initialization complete
[16:22:10.884][4] Found new device with v/p 05ac:12a8 at 1-3
[16:22:10.884][4] Setting configuration for device 1-3, from 1 to 4
[16:22:10.884][2] Could not set configuration 4 for device 1-3: LIBUSB_ERROR_BUSY
```

**Comment by cczhr** [comment]
应该是被miui的文件管理器占用了usb

**Comment by cczhr** [comment]
> 系统是MIUI12 EU稳定版全新安装完,Magisk Root,安装组件显示成功. 用type-c转接usb-a然后连iphone12,系统会自动跳出弹窗让我选择文件管理器打开,打开之后也可以显示iphone的照片. 退回软件可以显示USB授权,授权完成之后一直设备连接状态是“未挂载”,换了直连的线也不可以 能麻烦帮忙看看不?
> 
> ```
> node=/dev/bus/usb/001/003 fd=99
> [16:22:07.915][3] usbmuxd v1.1.2 starting up
> [16:22:07.921][3] Caught signal 15, exiting
> [16:22:07.921][3] Sending signal 15 to instance with pid 16878
> [16:22:07.921][4] Event processing interrupted
> [16:22:07.921][3] usbmuxd shutting down
> [16:22:10.875][3] usbmuxd v1.1.2 starting up
> [16:22:10.882][4] Creating socket
> [16:22:10.882][4] socket port:27015
> [16:22:10.882][4] Listening on /var/run/usbmuxd
> [16:22:10.882][4] Initializing USB
> [16:22:10.882][3] Using libusb 1.0.24
> [16:22:10.884][4] Registering for libusb hotplug events
> [16:22:10.884][4] Found new device with v/p 05ac:12a8 at 1-3
> [16:22:10.884][4] Setting configuration for device 1-3, from 1 to 4
> [16:22:10.884][2] Could not set configuration 4 for device 1-3: LIBUSB_ERROR_BUSY
> [16:22:10.884][4] 0 devices detected
> [16:22:10.884][3] Initialization complete
> [16:22:10.884][4] Found new device with v/p 05ac:12a8 at 1-3
> [16:22:10.884][4] Setting configuration for device 1-3, from 1 to 4
> [16:22:10.884][2] Could not set configuration 4 for device 1-3: LIBUSB_ERROR_BUSY
> ```

应该是被miui的文件管理器占用了usb

**Comment by iphp** [comment]
> Could not set configuration 4 for device 1-3: LIBUSB_ERROR_BUSY

同样问题,请问有解决方法么.

**Comment by cczhr** [comment]
> 系统是MIUI12 EU稳定版全新安装完,Magisk Root,安装组件显示成功. 用type-c转接usb-a然后连iphone12,系统会自动跳出弹窗让我选择文件管理器打开,打开之后也可以显示iphone的照片. 退回软件可以显示USB授权,授权完成之后一直设备连接状态是“未挂载”,换了直连的线也不可以 能麻烦帮忙看看不?
> 
> ```
> node=/dev/bus/usb/001/003 fd=99
> [16:22:07.915][3] usbmuxd v1.1.2 starting up
> [16:22:07.921][3] Caught signal 15, exiting
> [16:22:07.921][3] Sending signal 15 to instance with pid 16878
> [16:22:07.921][4] Event processing interrupted
> [16:22:07.921][3] usbmuxd shutting down
> [16:22:10.875][3] usbmuxd v1.1.2 starting up
> [16:22:10.882][4] Creating socket
> [16:22:10.882][4] socket port:27015
> [16:22:10.882][4] Listening on /var/run/usbmuxd
> [16:22:10.882][4] Initializing USB
> [16:22:10.882][3] Using libusb 1.0.24
> [16:22:10.884][4] Registering for libusb hotplug events
> [16:22:10.884][4] Found new device with v/p 05ac:12a8 at 1-3
> [16:22:10.884][4] Setting configuration for device 1-3, from 1 to 4
> [16:22:10.884][2] Could not set configuration 4 for device 1-3: LIBUSB_ERROR_BUSY
> [16:22:10.884][4] 0 devices detected
> [16:22:10.884][3] Initialization complete
> [16:22:10.884][4] Found new device with v/p 05ac:12a8 at 1-3
> [16:22:10.884][4] Setting configuration for device 1-3, from 1 to 4
> [16:22:10.884][2] Could not set configuration 4 for device 1-3: LIBUSB_ERROR_BUSY
> ```
可以试试我新发的这个看看行不行（解压后提取apk安装）
https://github.com/cczhr/OTGLocation/files/9018238/app-release.zip

**Comment by iphp** [comment]
> > 系统是MIUI12 EU稳定版全新安装完,Magisk Root,安装组件显示成功. 用type-c转接usb-a然后连iphone12,系统会自动跳出弹窗让我选择文件管理器打开,打开之后也可以显示iphone的照片. 退回软件可以显示USB授权,授权完成之后一直设备连接状态是“未挂载”,换了直连的线也不可以 能麻烦帮忙看看不?
> > ```
> > node=/dev/bus/usb/001/003 fd=99
> > [16:22:07.915][3] usbmuxd v1.1.2 starting up
> > [16:22:07.921][3] Caught signal 15, exiting
> > [16:22:07.921][3] Sending signal 15 to instance with pid 16878
> > [16:22:07.921][4] Event processing interrupted
> > [16:22:07.921][3] usbmuxd shutting down
> > [16:22:10.875][3] usbmuxd v1.1.2 starting up
> > [16:22:10.882][4] Creating socket
> > [16:22:10.882][4] socket port:27015
> > [16:22:10.882][4] Listening on /var/run/usbmuxd
> > [16:22:10.882][4] Initializing USB
> > [16:22:10.882][3] Using libusb 1.0.24
> > [16:22:10.884][4] Registering for libusb hotplug events
> > [16:22:10.884][4] Found new device with v/p 05ac:12a8 at 1-3
> > [16:22:10.884][4] Setting configuration for device 1-3, from 1 to 4
> > [16:22:10.884][2] Could not set configuration 4 for device 1-3: LIBUSB_ERROR_BUSY
> > [16:22:10.884][4] 0 devices detected
> > [16:22:10.884][3] Initialization complete
> > [16:22:10.884][4] Found new device with v/p 05ac:12a8 at 1-3
> > [16:22:10.884][4] Setting configuration for device 1-3, from 1 to 4
> > [16:22:10.884][2] Could not set configuration 4 for device 1-3: LIBUSB_ERROR_BUSY
> > ```
> 
> 可以试试我新发的这个看看行不行（解压后提取apk安装） https://github.com/cczhr/OTGLocation/files/9018238/app-release.zip
在我的小米12X上不行，要闪退。

**Comment by cczhr** [comment]
> > > 系统是MIUI12 EU稳定版全新安装完,Magisk Root,安装组件显示成功. 用type-c转接usb-a然后连iphone12,系统会自动跳出弹窗让我选择文件管理器打开,打开之后也可以显示iphone的照片. 退回软件可以显示USB授权,授权完成之后一直设备连接状态是“未挂载”,换了直连的线也不可以 能麻烦帮忙看看不?
> > > ```
> > > node=/dev/bus/usb/001/003 fd=99
> > > [16:22:07.915][3] usbmuxd v1.1.2 starting up
> > > [16:22:07.921][3] Caught signal 15, exiting
> > > [16:22:07.921][3] Sending signal 15 to instance with pid 16878
> > > [16:22:07.921][4] Event processing interrupted
> > > [16:22:07.921][3] usbmuxd shutting down
> > > [16:22:10.875][3] usbmuxd v1.1.2 starting up
> > > [16:22:10.882][4] Creating socket
> > > [16:22:10.882][4] socket port:27015
> > > [16:22:10.882][4] Listening on /var/run/usbmuxd
> > > [16:22:10.882][4] Initializing USB
> > > [16:22:10.882][3] Using libusb 1.0.24
> > > [16:22:10.884][4] Registering for libusb hotplug events
> > > [16:22:10.884][4] Found new device with v/p 05ac:12a8 at 1-3
> > > [16:22:10.884][4] Setting configuration for device 1-3, from 1 to 4
> > > [16:22:10.884][2] Could not set configuration 4 for device 1-3: LIBUSB_ERROR_BUSY
> > > [16:22:10.884][4] 0 devices detected
> > > [16:22:10.884][3] Initialization complete
> > > [16:22:10.884][4] Found new device with v/p 05ac:12a8 at 1-3
> > > [16:22:10.884][4] Setting configuration for device 1-3, from 1 to 4
> > > [16:22:10.884][2] Could not set configuration 4 for device 1-3: LIBUSB_ERROR_BUSY
> > > ```
> > 
> > 
> > 可以试试我新发的这个看看行不行（解压后提取apk安装） https://github.com/cczhr/OTGLocation/files/9018238/app-release.zip
> > 在我的小米12X上不行，要闪退。
现在应该可以了 我找了台小米试了下
https://github.com/cczhr/OTGLocation/releases/tag/V1.1.5
