### ISSUE TITLE
iOS 16.0 正式版无法使用，提示驱动安装失败

### ISSUE THREAD

**Issue by yeatce** [cczhr/OTGLocation#18]
Yeatce's iPhone 13 mini
16.0
Uploading /sdcard/lockdown/drivers/16.0/DeveloperDiskImage.dmg
done.
Mounting...
Error: ImageMountFailed
ImageSignature[0]: 
Status: Complete

目录、驱动文件均无问题，望排查修复

**Comment by BlingRbt** [comment]
同上
两个地方下载的库 都提示失败
一个提示 Error: mount_image return -3
另一个提示 Error: ImageMountFailed

**Comment by cczhr** [comment]
@BlingRbt  @yeatce 
有打开开发者模式么（我手机还没升级到16 今晚试试
![image](https://user-images.githubusercontent.com/20502238/190961541-33d1e9a8-a81d-4f13-b3cd-c1bfeae50778.png)

**Comment by cczhr** [comment]
@BlingRbt @yeatce  确实是因为ios新增了开发者模式选项的问题，已经适配，可以安装最新版本试试 ，参考使用说明#19 。

**Comment by yeatce** [comment]
感谢！升级完iOS16后设置里面找不到开发者选项了，按照菊苣的新版本说明一切正常了，好耶！
