### ISSUE TITLE
美洲，澳洲一直到格陵兰岛，南极洲，改位置没用。

### ISSUE THREAD

**Issue by sunulin** [cczhr/OTGLocation#2]
穿过白令海峡到格陵兰岛 的美洲 澳洲以及南极洲无法修改

**Comment by cczhr** [comment]
> 穿过白令海峡到格陵兰岛 的美洲 澳洲以及南极洲无法修改

你好，麻烦说下操作步骤。

**Comment by cczhr** [comment]
操作后发现 带负数的坐标,无法正常修改位置 。已修复此问题 待更新

**Comment by cczhr** [comment]
> 穿过白令海峡到格陵兰岛 的美洲 澳洲以及南极洲无法修改
已修复 试试新版本 https://github.com/cczhr/OTGLocation/releases/tag/V1.1.0
