### ISSUE TITLE
android10，iOS15.6.1连接后找不到文件

### ISSUE THREAD

**Issue by df13954** [cczhr/OTGLocation#20]
![screenshot_3-0429_102530](https://user-images.githubusercontent.com/18607031/235279459-1e2d059f-e8dc-451c-827c-2cd4bdd124c3.png)
![screenshot_3-0429_102536](https://user-images.githubusercontent.com/18607031/235279467-f2302693-c719-4dc5-930a-b8c350d99979.png)

APP已经授权root，两台手机连接之后开始显示日志，如图

**Comment by cczhr** [comment]
![image](https://user-images.githubusercontent.com/20502238/236083497-eccf1714-8a75-4e85-82e9-7c37abc9241d.png)点击了安装组件没

**Comment by df13954** [comment]
> ![image](https://user-images.githubusercontent.com/20502238/236083497-eccf1714-8a75-4e85-82e9-7c37abc9241d.png)点击了安装组件没

没呢，因为不知道整个流程，我今晚回去试试

**Comment by cczhr** [comment]
![image](https://user-images.githubusercontent.com/20502238/236146073-9bf1bf35-b280-47fe-afcc-42d813d79311.png)
可以点击 关于/帮助 看看使用说明

**Comment by df13954** [comment]
> ![image](https://user-images.githubusercontent.com/20502238/236146073-9bf1bf35-b280-47fe-afcc-42d813d79311.png) 可以点击 关于/帮助 看看使用说明

成功了，哈哈
