### ISSUE TITLE
已发现问题

### ISSUE THREAD

**Issue by cczhr** [cczhr/OTGLocation#3]
1.有些机型 运行显示"CANNOT LINK EXECUTABLE" 字样导致无法正常使用，原因是设置LD_LIBRARY_PATH无效（待修复）  
2.socket port被其它应用占用问题，日志显示“bind() failed: Address already in use” 字样（已修复 待验证）

**Comment by daomeixiong2547** [comment]
我手动将文件复制到system/lib 和 system/bin下，也会报CANNOT LINK EXECUTABLE "./system/bin/usbmuxd": library "libusb-1.0.so" not found

**Comment by cczhr** [comment]
> CANNOT LINK EXECUTABLE
 你这是有打开过OTGLocation？如果有的话可能设了这LD_LIBRARY_PATH吧，可以重启试试，还有放进 system/lib的文件权限为0644   system/bin的文件权限0755

**Comment by cczhr** [comment]
> 我手动将文件复制到system/lib 和 system/bin下，也会报CANNOT LINK EXECUTABLE "./system/bin/usbmuxd": library "libusb-1.0.so" not found

你这是有打开过OTGLocation？如果有的话可能设了这LD_LIBRARY_PATH吧，可以重启试试，还有放进 system/lib的文件权限为0644 system/bin的文件权限0755

**Comment by daomeixiong2547** [comment]
> LD_LIBRARY_PATH吧，可以重启试试，还有放进 system/lib的文件权限为0644 system/bin的文件权限0755

我试了一下，因为我是使用的genymotion模拟器去跑的，我安装了一个更换cpu架构的插件，放在system/lib/arm下就能找到了，但是genymotion模拟器设置LD_LIBRARY_PATH确实没有生效，不然就可以到/data的目录下去找文件了。我这边看看有么有真机的root设备再研究一下。

**Comment by czhixin** [comment]
您好，我遇到个问题是点击安装组件，提示组件已安装。上面组件安装状态还是false，请问这个组件安装的是什么？

**Comment by cczhr** [comment]
> 您好，我遇到个问题是点击安装组件，提示组件已安装。上面组件安装状态还是false，请问这个组件安装的是什么？

你好

“请问这个组件安装的是什么” 
https://github.com/cczhr/OTGLocation/tree/master/app/src/main/assets 把这个路径的下的文件 放到android设备这个路径 /data/local/tmp

“安装状态还是false” 
app获取root权限了么，因为这个app需要root权限才能正常使用
