### ISSUE TITLE
Android Studio 可以引入libimobiledevice源码进行编码？

### ISSUE THREAD

**Issue by daomeixiong2547** [cczhr/OTGLocation#4]
Android Studio 可以引入libimobiledevice源码进行编译吗？

**Comment by cczhr** [comment]
> Android Studio 可以引入libimobiledevice源码进行编译吗？

不行

**Comment by daomeixiong2547** [comment]
> > Android Studio 可以引入libimobiledevice源码进行编译吗？
> 
> 不行

只能使用ndk-pkg编译出运行库，集成之后使用吗？请问你另外一个资源里的是使用什么编译出来的呀？

**Comment by cczhr** [comment]
> > > Android Studio 可以引入libimobiledevice源码进行编译吗？
> > 
> > 
> > 不行
> 
> 只能使用ndk-pkg编译出运行库，集成之后使用吗？请问你另外一个资源里的是使用什么编译出来的呀？

参考这个 https://developer.android.com/ndk/guides/standalone_toolchain?hl=zh-cn

**Comment by cczhr** [comment]
> > > Android Studio 可以引入libimobiledevice源码进行编译吗？
> > 
> > 
> > 不行
> 
> 只能使用ndk-pkg编译出运行库，集成之后使用吗？请问你另外一个资源里的是使用什么编译出来的呀？

可以搜搜Android交叉编译的资料

**Comment by daomeixiong2547** [comment]
> > > > Android Studio 可以引入libimobiledevice源码进行编译吗？
> > > 
> > > 
> > > 不行
> > 
> > 
> > 只能使用ndk-pkg编译出运行库，集成之后使用吗？请问你另外一个资源里的是使用什么编译出来的呀？
> 
> 可以搜搜Android交叉编译的资料

我研究一下，谢谢~

**Comment by daomeixiong2547** [comment]
> > > > Android Studio 可以引入libimobiledevice源码进行编译吗？
> > > 
> > > 
> > > 不行
> > 
> > 
> > 只能使用ndk-pkg编译出运行库，集成之后使用吗？请问你另外一个资源里的是使用什么编译出来的呀？
> 
> 可以搜搜Android交叉编译的资料

![image](https://user-images.githubusercontent.com/43061787/112124406-437a3000-8bfd-11eb-9d57-41778559f2ef.png)

我编译好了，但是和你的工程有些区别
请问你assets下的bin文件夹有什么特殊作用吗？
